# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'rnkit' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for rnkit



  rn_path = '../node_modules/react-native'
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTPushNotification',
    'RCTWebSocket'
  ]

  pod 'RNImageCropPicker', :path =>  '../node_modules/react-native-image-crop-picker'
  pod 'react-native-fast-image', :path => '../node_modules/react-native-fast-image'
  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'
  pod 'RNSVG', :path => '../node_modules/react-native-svg'




  pod 'react-native-camera', :path => '../node_modules/react-native-camera'

  pod 'Picker', :path => '../node_modules/react-native-picker'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      targets_to_ignore = %w(React yoga)

      if targets_to_ignore.include? target.name
        target.remove_from_project
      end
      # if target.name == "React"
      #   target.remove_from_project
      # end
    end
  end

end
#
# target 'rnkit-tvOS' do
#   # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
#   # use_frameworks!
#
#   # Pods for rnkit-tvOS
#
#   target 'rnkit-tvOSTests' do
#     inherit! :search_paths
#     # Pods for testing
#   end
#
# end
