import React, { PureComponent as Component } from 'react'
import { Text as RNText, Platform } from 'react-native'
import { View } from '../Layouts'

import { material } from 'react-native-typography'

import faker from '../../../vendors/faker.min.js'

export class Text extends Component {

  render() {
    let {
      style,
      theme = 'H3',
      align = 'left',
      size,
      color,
      children = faker.commerce.productName(),
      ...props
    } = this.props
    let themeStyle = {...styles[theme]} //!!!
    color && themeStyle && (themeStyle.color = color)
    size && themeStyle && (themeStyle.fontSize = size)
    return <RNText
      // numberOfLines={1}
      // flex={1}
      style={{
        // alignSelf: 'flex-start',
        // textAlign: align,
        textAlignVertical: 'bottom',
        // borderWidth: 1,
        ...textShadow,
        ...themeStyle,
        ...style,
      }}
      {...props}
      >
        {children}
      </RNText>
    }
  }

  const textShadow = {
    textShadowColor: 'rgba(0, 0, 0, 0.5)',
    textShadowOffset: {width: -0.2, height: 0.2},
    textShadowRadius: 0.1
  }


  const styles = {
    H1: {
      fontSize: 26,
      // lineHeight: 36 * 1.5,
      fontWeight: 'bold',
      color: 'rgba(0,0,0,.93)'
    },
    H2: {
      fontSize: 24,
      // lineHeight: 24 * 1.5,
      fontWeight: '900',
      color: 'rgba(0,0,0,.9)'
    },
    H3: {
      fontSize: 22,
      // lineHeight: 22 * 1.5,
      fontWeight: '800',
      color: 'rgba(0,0,0,.85)'
    },
    H4: {
      fontSize: 20,
      // lineHeight: 20 * 1.5,
      fontWeight: '700',
      color: 'rgba(0,0,0,.80)'
    },
    H5: {
      fontSize: 18,
      // lineHeight: 18 * 1.5,
      fontWeight: '600',
      color: 'rgba(0,0,0,.80)'
    },
    H6: {
      fontSize: 16,
      // lineHeight: 16 * 1.5,
      fontWeight: '200',
      color: 'rgba(0,0,0,.75)'
    },
    H7: {
      fontSize: 14,
      // lineHeight: 14 * 1.5,
      fontWeight: '200',
      color: 'rgba(0,0,0,.70)'
    },
    H8: {
      fontSize: 12,
      // lineHeight: 12 * 1.5,
      fontWeight: '100',
      color: 'rgba(0,0,0,.70)'
    },
    H9: {
      fontSize: 10,
      // lineHeight: 10 * 1.5,
      fontWeight: '100',
      color: 'rgba(0,0,0,.70)'
    },
  }



  const IOS_FONTS = [
    'AcademyEngravedLetPlain',
    'AlNile',
    'AlNile-Bold',
    'AmericanTypewriter',
    'AmericanTypewriter-Bold',
    'AmericanTypewriter-Condensed',
    'AmericanTypewriter-CondensedBold',
    'AmericanTypewriter-CondensedLight',
    'AmericanTypewriter-Light',
    'AmericanTypewriter-Semibold',
    'AppleColorEmoji',
    'AppleSDGothicNeo-Bold',
    'AppleSDGothicNeo-Light',
    'AppleSDGothicNeo-Medium',
    'AppleSDGothicNeo-Regular',
    'AppleSDGothicNeo-SemiBold',
    'AppleSDGothicNeo-Thin',
    'AppleSDGothicNeo-UltraLight',
    'Arial-BoldItalicMT',
    'Arial-BoldMT',
    'Arial-ItalicMT',
    'ArialMT',
    'ArialHebrew',
    'ArialHebrew-Bold',
    'ArialHebrew-Light',
    'ArialRoundedMTBold',
    'Avenir-Black',
    'Avenir-BlackOblique',
    'Avenir-Book',
    'Avenir-BookOblique',
    'Avenir-Heavy',
    'Avenir-HeavyOblique',
    'Avenir-Light',
    'Avenir-LightOblique',
    'Avenir-Medium',
    'Avenir-MediumOblique',
    'Avenir-Oblique',
    'Avenir-Roman',
    'AvenirNext-Bold',
    'AvenirNext-BoldItalic',
    'AvenirNext-DemiBold',
    'AvenirNext-DemiBoldItalic',
    'AvenirNext-Heavy',
    'AvenirNext-HeavyItalic',
    'AvenirNext-Italic',
    'AvenirNext-Medium',
    'AvenirNext-MediumItalic',
    'AvenirNext-Regular',
    'AvenirNext-UltraLight',
    'AvenirNext-UltraLightItalic',
    'AvenirNextCondensed-Bold',
    'AvenirNextCondensed-BoldItalic',
    'AvenirNextCondensed-DemiBold',
    'AvenirNextCondensed-DemiBoldItalic',
    'AvenirNextCondensed-Heavy',
    'AvenirNextCondensed-HeavyItalic',
    'AvenirNextCondensed-Italic',
    'AvenirNextCondensed-Medium',
    'AvenirNextCondensed-MediumItalic',
    'AvenirNextCondensed-Regular',
    'AvenirNextCondensed-UltraLight',
    'AvenirNextCondensed-UltraLightItalic',
    'Baskerville',
    'Baskerville-Bold',
    'Baskerville-BoldItalic',
    'Baskerville-Italic',
    'Baskerville-SemiBold',
    'Baskerville-SemiBoldItalic',
    'BodoniSvtyTwoITCTT-Bold',
    'BodoniSvtyTwoITCTT-Book',
    'BodoniSvtyTwoITCTT-BookIta',
    'BodoniSvtyTwoOSITCTT-Bold',
    'BodoniSvtyTwoOSITCTT-Book',
    'BodoniSvtyTwoOSITCTT-BookIt',
    'BodoniSvtyTwoSCITCTT-Book',
    'BodoniOrnamentsITCTT',
    'BradleyHandITCTT-Bold',
    'ChalkboardSE-Bold',
    'ChalkboardSE-Light',
    'ChalkboardSE-Regular',
    'Chalkduster',
    'Charter-Black',
    'Charter-BlackItalic',
    'Charter-Bold',
    'Charter-BoldItalic',
    'Charter-Italic',
    'Charter-Roman',
    'Cochin',
    'Cochin-Bold',
    'Cochin-BoldItalic',
    'Cochin-Italic',
    'Copperplate',
    'Copperplate-Bold',
    'Copperplate-Light',
    'Courier',
    'Courier-Bold',
    'Courier-BoldOblique',
    'Courier-Oblique',
    'CourierNewPS-BoldItalicMT',
    'CourierNewPS-BoldMT',
    'CourierNewPS-ItalicMT',
    'CourierNewPSMT',
    'DINAlternate-Bold',
    'DINCondensed-Bold',
    'Damascus',
    'DamascusBold',
    'DamascusLight',
    'DamascusMedium',
    'DamascusSemiBold',
    'DevanagariSangamMN',
    'DevanagariSangamMN-Bold',
    'Didot',
    'Didot-Bold',
    'Didot-Italic',
    'EuphemiaUCAS',
    'EuphemiaUCAS-Bold',
    'EuphemiaUCAS-Italic',
    'Farah',
    'Futura-Bold',
    'Futura-CondensedExtraBold',
    'Futura-CondensedMedium',
    'Futura-Medium',
    'Futura-MediumItalic',
    'GeezaPro',
    'GeezaPro-Bold',
    'Georgia',
    'Georgia-Bold',
    'Georgia-BoldItalic',
    'Georgia-Italic',
    'GillSans',
    'GillSans-Bold',
    'GillSans-BoldItalic',
    'GillSans-Italic',
    'GillSans-Light',
    'GillSans-LightItalic',
    'GillSans-SemiBold',
    'GillSans-SemiBoldItalic',
    'GillSans-UltraBold',
    'GujaratiSangamMN',
    'GujaratiSangamMN-Bold',
    'GurmukhiMN',
    'GurmukhiMN-Bold',
    'Helvetica',
    'Helvetica-Bold',
    'Helvetica-BoldOblique',
    'Helvetica-Light',
    'Helvetica-LightOblique',
    'Helvetica-Oblique',
    'HelveticaNeue',
    'HelveticaNeue-Bold',
    'HelveticaNeue-BoldItalic',
    'HelveticaNeue-CondensedBlack',
    'HelveticaNeue-CondensedBold',
    'HelveticaNeue-Italic',
    'HelveticaNeue-Light',
    'HelveticaNeue-LightItalic',
    'HelveticaNeue-Medium',
    'HelveticaNeue-MediumItalic',
    'HelveticaNeue-Thin',
    'HelveticaNeue-ThinItalic',
    'HelveticaNeue-UltraLight',
    'HelveticaNeue-UltraLightItalic',
    'HiraMaruProN-W4',
    'HiraMinProN-W3',
    'HiraMinProN-W6',
    'HiraginoSans-W3',
    'HiraginoSans-W6',
    'HoeflerText-Black',
    'HoeflerText-BlackItalic',
    'HoeflerText-Italic',
    'HoeflerText-Regular',
    'Kailasa',
    'Kailasa-Bold',
    'KannadaSangamMN',
    'KannadaSangamMN-Bold',
    'Kefa-Regular',
    'KhmerSangamMN',
    'KohinoorBangla-Light',
    'KohinoorBangla-Regular',
    'KohinoorBangla-Semibold',
    'KohinoorDevanagari-Light',
    'KohinoorDevanagari-Regular',
    'KohinoorDevanagari-Semibold',
    'KohinoorTelugu-Light',
    'KohinoorTelugu-Medium',
    'KohinoorTelugu-Regular',
    'LaoSangamMN',
    'MalayalamSangamMN',
    'MalayalamSangamMN-Bold',
    'MarkerFelt-Thin',
    'MarkerFelt-Wide',
    'Menlo-Bold',
    'Menlo-BoldItalic',
    'Menlo-Italic',
    'Menlo-Regular',
    'DiwanMishafi',
    'MyanmarSangamMN',
    'MyanmarSangamMN-Bold',
    'Noteworthy-Bold',
    'Noteworthy-Light',
    'NotoNastaliqUrdu',
    // 'NotoSansChakma-Regular',
    'Optima-Bold',
    'Optima-BoldItalic',
    'Optima-ExtraBlack',
    'Optima-Italic',
    'Optima-Regular',
    'OriyaSangamMN',
    'OriyaSangamMN-Bold',
    'Palatino-Bold',
    'Palatino-BoldItalic',
    'Palatino-Italic',
    'Palatino-Roman',
    'Papyrus',
    'Papyrus-Condensed',
    'PartyLetPlain',
    'PingFangHK-Light',
    'PingFangHK-Medium',
    'PingFangHK-Regular',
    'PingFangHK-Semibold',
    'PingFangHK-Thin',
    'PingFangHK-Ultralight',
    'PingFangSC-Light',
    'PingFangSC-Medium',
    'PingFangSC-Regular',
    'PingFangSC-Semibold',
    'PingFangSC-Thin',
    'PingFangSC-Ultralight',
    'PingFangTC-Light',
    'PingFangTC-Medium',
    'PingFangTC-Regular',
    'PingFangTC-Semibold',
    'PingFangTC-Thin',
    'PingFangTC-Ultralight',
    'Rockwell-Bold',
    'Rockwell-BoldItalic',
    'Rockwell-Italic',
    'Rockwell-Regular',
    'SavoyeLetPlain',
    'SinhalaSangamMN',
    'SinhalaSangamMN-Bold',
    'SnellRoundhand',
    'SnellRoundhand-Black',
    'SnellRoundhand-Bold',
    'Symbol',
    'TamilSangamMN',
    'TamilSangamMN-Bold',
    'Thonburi',
    'Thonburi-Bold',
    'Thonburi-Light',
    'TimesNewRomanPS-BoldItalicMT',
    'TimesNewRomanPS-BoldMT',
    'TimesNewRomanPS-ItalicMT',
    'TimesNewRomanPSMT',
    'Trebuchet-BoldItalic',
    'TrebuchetMS',
    'TrebuchetMS-Bold',
    'TrebuchetMS-Italic',
    'Verdana',
    'Verdana-Bold',
    'Verdana-BoldItalic',
    'Verdana-Italic',
    'ZapfDingbatsITC',
    'Zapfino',
  ]


  const ANDROID_FONTS = [
    'Roboto Thin',
    'Roboto Light',
    'Roboto Regular',
    'Roboto Bold',
    'Roboto Medium',
    'Roboto Black',
    'Roboto Condensed Light',
    'Roboto Condensed Regular',
    'Roboto Condensed Medium',
    'Roboto Condensed Bold',
    'Noto Serif',
    'Noto Serif Bold',
    'Droid Sans Mono',
    'Cutive Mono',
    'Coming Soon',
    'Dancing Script',
    'Dancing Script Bold',
    'Carrois Gothic SC'
  ]

    export const FontList = Platform.select({
      ios: IOS_FONTS,
      // ['Palatino-Bold', 'GillSans-Bold', 'AmericanTypewriter-CondensedBold', 'KohinoorBangla-Semibold', 'Didot', 'Georgia', 'HelveticaNeue', 'Kailasa', 'Zapfino', 'GillSans']
      // color: 'red'
      // android: ANDROID_FONTS
      android: ['Roboto', 'Serif Regular', 'Pacifico', 'monospace',, 'Noto Sans']
    })
